apiVersion: v1
kind: ConfigMap
metadata:
  name: googi-config
  namespace: googi
  labels:
    app: googi

data:
  # Example non‑secret env vars
  APP_NAME: "GOOGI"
  LOG_LEVEL: "INFO"
  CORS_ORIGINS: "*"
