apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: googi-hpa-backend
  namespace: googi-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: googi-backend
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
