apiVersion: v1
kind: Secret
metadata:
  name: docintel-secret
  namespace: docintel
  labels:
    app.kubernetes.io/name: docintel-secret
    app.kubernetes.io/part-of: docintel-platform
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CHANGE_IN_PRODUCTION"
  DATABASE_URL: "postgresql://postgres:CHANGE_IN_PRODUCTION@postgres:5432/docintel"
  REDIS_PASSWORD: ""
  RABBITMQ_USER: "docintel_user"
  RABBITMQ_PASS: "CHANGE_IN_PRODUCTION"
  JWT_SECRET_KEY: "CHANGE_TO_STRONG_RANDOM_SECRET_KEY"
  GEMINI_API_KEY: ""
