"""initial_migration

Revision ID: 139dd4fc19e7
Revises: 
Create Date: 2026-06-23 17:24:35.756500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database


# revision identifiers, used by Alembic.
revision: str = '139dd4fc19e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawled_pages',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('page_content', sa.Text(), nullable=True),
    sa.Column('page_hash', sa.String(length=64), nullable=True),
    sa.Column('pagerank', sa.Float(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawled_pages_url'), 'crawled_pages', ['url'], unique=True)
    op.create_table('page_links',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('target_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_links_source_url'), 'page_links', ['source_url'], unique=False)
    op.create_index(op.f('ix_page_links_target_url'), 'page_links', ['target_url'], unique=False)
    op.create_table('search_logs',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_logs_query_text'), 'search_logs', ['query_text'], unique=False)
    op.create_table('users',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'REVIEWER', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('INVOICE', 'RFQ', 'PURCHASE_ORDER', 'CONTRACT', 'COMPLIANCE', 'UNKNOWN', name='documentcategory'), nullable=False),
    sa.Column('status', sa.Enum('INGESTED', 'PROCESSING', 'FAILED', 'AWAITING_REVIEW', 'PROCESSED', name='documentstatus'), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('consensus_score', sa.Float(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by', app.database.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('document_id', app.database.GUID(), nullable=True),
    sa.Column('user_id', app.database.GUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_fields',
    sa.Column('id', app.database.GUID(), nullable=False),
    sa.Column('document_id', app.database.GUID(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('extracted_value', sa.String(), nullable=True),
    sa.Column('critic_score', sa.Float(), nullable=True),
    sa.Column('auditor_score', sa.Float(), nullable=True),
    sa.Column('consensus_value', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_modified', sa.Boolean(), nullable=True),
    sa.Column('validation_status', sa.Enum('VALID', 'FLAGGED', 'MANUAL_CORRECTION', name='fieldvalidationstatus'), nullable=False),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extracted_fields')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_search_logs_query_text'), table_name='search_logs')
    op.drop_table('search_logs')
    op.drop_index(op.f('ix_page_links_target_url'), table_name='page_links')
    op.drop_index(op.f('ix_page_links_source_url'), table_name='page_links')
    op.drop_table('page_links')
    op.drop_index(op.f('ix_crawled_pages_url'), table_name='crawled_pages')
    op.drop_table('crawled_pages')
    # ### end Alembic commands ###
