"""add_email_verification_fields

Revision ID: 2609d3dbe6e4
Revises: 4f8a2c9d1e03
Create Date: 2026-07-07 21:43:17.182825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app


# revision identifiers, used by Alembic.
revision: str = '2609d3dbe6e4'
down_revision: Union[str, None] = '4f8a2c9d1e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_configs_event_type'), table_name='webhook_configs')
    op.drop_table('webhook_configs')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_webhook_logs_idempotency_key'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.add_column('documents', sa.Column('assigned_to_id', app.database.GUID(), nullable=True))
    op.add_column('documents', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('approval_stage', sa.String(), nullable=False))
    op.drop_index(op.f('ix_documents_category_uploaded_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_status_created_at'), table_name='documents')
    op.create_foreign_key(None, 'documents', 'users', ['assigned_to_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_search_logs_query_created'), table_name='search_logs')
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('users', sa.Column('verification_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token_expires_at')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_verified')
    op.create_index(op.f('ix_search_logs_query_created'), 'search_logs', ['query_text', 'created_at'], unique=False)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_index(op.f('ix_documents_status_created_at'), 'documents', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_documents_category_uploaded_by'), 'documents', ['category', 'uploaded_by'], unique=False)
    op.drop_column('documents', 'approval_stage')
    op.drop_column('documents', 'due_date')
    op.drop_column('documents', 'assigned_to_id')
    op.create_table('webhook_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('webhook_config_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('webhook_logs_pkey'))
    )
    op.create_index(op.f('ix_webhook_logs_idempotency_key'), 'webhook_logs', ['idempotency_key'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('webhook_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('webhook_configs_pkey'))
    )
    op.create_index(op.f('ix_webhook_configs_event_type'), 'webhook_configs', ['event_type'], unique=False)
    # ### end Alembic commands ###
