import json
import logging
import time

import pika
from sqlalchemy.orm import Session

from app.agents.consensus import run_agent_consensus
from app.config import settings
from app.database import SessionLocal
from app.models.audit import AuditLog
from app.models.document import Document, DocumentCategory, DocumentStatus, ExtractedField
from app.services.ocr import perform_ocr
from app.services.queue import register_local_worker_callback, register_local_crawl_worker_callback
from app.services.vector_store import add_document_to_vector_store

# Setup logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger("worker")

# Retry / DLQ constants
MAX_RETRIES = 3
DLX_EXCHANGE = "document_dlx"
DLQ_QUEUE = "document_processing_dlq"
MAIN_QUEUE = "document_processing_queue"
CRAWL_QUEUE = "crawl_queue"

def classify_document(filename: str, ocr_text: str) -> DocumentCategory:
    """
    Classifies a document based on filename patterns and our custom LocalNaiveBayesClassifier.
    """
    from app.services.local_engine import LocalNaiveBayesClassifier
    
    fn = filename.lower()
    if "invoice" in fn:
        return DocumentCategory.INVOICE
    elif "rfq" in fn:
        return DocumentCategory.RFQ
    elif "contract" in fn or "agreement" in fn:
        return DocumentCategory.CONTRACT
    elif "compliance" in fn or "certificate" in fn:
        return DocumentCategory.COMPLIANCE

    best_class, _ = LocalNaiveBayesClassifier.classify(ocr_text)
    try:
        return DocumentCategory[best_class]
    except KeyError:
        return DocumentCategory.UNKNOWN

def process_document(document_id: str):
    """
    Synchronous processing core for a single document ID.
    Used by both RabbitMQ worker daemon and the threading fallback.
    """
    db: Session = SessionLocal()
    try:
        doc = db.query(Document).filter(Document.id == document_id).first()
        if not doc:
            logger.error(f"Document {document_id} not found in database.")
            return

        logger.info(f"Worker processing document {doc.id} ({doc.filename})...")

        # 1. Update status
        doc.status = DocumentStatus.PROCESSING
        db.commit()

        # 2. Perform OCR (using Redis distributed semaphore to prevent process-level Tesseract congestion)
        from app.services.cache import acquire_redis_semaphore, release_redis_semaphore
        owner_id = None
        for _ in range(60):
            owner_id = acquire_redis_semaphore("ocr", limit=4, timeout=120)
            if owner_id:
                break
            time.sleep(1.0)
            
        if not owner_id:
            owner_id = f"fallback_worker:{doc.id}"

        try:
            logger.info(f"Extracting text via OCR for {doc.filename}")
            ocr_result = perform_ocr(doc.file_path, doc.filename, doc.file_type)
        finally:
            release_redis_semaphore("ocr", owner_id)
            
        doc.ocr_text = ocr_result
        db.commit()

        # 3. Classification
        category = classify_document(doc.filename, ocr_result)
        doc.category = category
        db.commit()
        logger.info(f"Classified document {doc.id} as {category.value}")

        # 4. Run Multi-Agent Consensus Validation
        import asyncio
        consensus = asyncio.run(run_agent_consensus(ocr_result, category))

        # Save Extracted Fields
        # Remove any existing fields first (in case of re-processing)
        db.query(ExtractedField).filter(ExtractedField.document_id == doc.id).delete()

        for field in consensus["fields"]:
            db_field = ExtractedField(
                document_id=doc.id,
                field_key=field["field_key"],
                extracted_value=field["extracted_value"],
                critic_score=field["critic_score"],
                auditor_score=field["auditor_score"],
                consensus_value=field["consensus_value"],
                confidence_score=field["confidence_score"],
                is_modified=field["is_modified"],
                validation_status=field["validation_status"],
                validation_notes=field["validation_notes"]
            )
            db.add(db_field)

        doc.consensus_score = consensus["overall_score"]

        # Store executive summary generated by Summary Agent
        if consensus.get("executive_summary"):
            doc.executive_summary = consensus["executive_summary"]

        # 5. Check if any fields were FLAGGED, drift critical, or score is low
        has_flagged_fields = any(f["validation_status"] == "FLAGGED" for f in consensus["fields"])
        has_critical_drift = any(
            d.get("severity") == "CRITICAL" for d in consensus.get("drift_flags", [])
        )

        if consensus["overall_score"] >= 0.85 and not has_flagged_fields and not has_critical_drift:
            doc.status = DocumentStatus.PROCESSED
            logger.info(f"Document {doc.id} approved automatically (Score: {doc.consensus_score:.2%})")
        else:
            doc.status = DocumentStatus.AWAITING_REVIEW
            logger.info(f"Document {doc.id} flagged for human review (Score: {doc.consensus_score:.2%})")

        db.commit()

        # 6. Index in Vector Store
        metadata = {
            "filename": doc.filename,
            "category": doc.category.value,
            "status": doc.status.value,
        }
        add_document_to_vector_store(doc.id, ocr_result, metadata)

        # 7. Write Audit Log
        audit = AuditLog(
            document_id=doc.id,
            action="SYSTEM_PROCESSING_COMPLETE",
            details={
                "category": doc.category.value,
                "consensus_score": doc.consensus_score,
                "status": doc.status.value,
                "fields_extracted": len(consensus["fields"]),
                "drift_flags": consensus.get("drift_flags", []),
                "executive_summary": consensus.get("executive_summary", ""),
            }
        )
        db.add(audit)
        db.commit()
        logger.info(f"Successfully finished processing document {doc.id}")

    except Exception as e:
        logger.exception(f"Fatal error while worker processed document {document_id}: {str(e)}")
        # Attempt to set document status as FAILED
        try:
            doc = db.query(Document).filter(Document.id == document_id).first()
            if doc:
                doc.status = DocumentStatus.FAILED
                db.commit()
        except Exception as err:
            logger.error(f"Failed to set document status to FAILED: {err}")
        # Re-raise so that the RabbitMQ callback can handle retries
        raise
    finally:
        db.close()

# Register local thread runner callback in publisher module
register_local_worker_callback(process_document)


def process_crawl_task(url: str, max_depth: int = 2):
    """
    Synchronous crawl task execution for worker daemon and local thread fallback.
    Invokes backend crawl service to fetch pages, store metadata in DB,
    index into ChromaDB vector store, and update PageRank.
    """
    from app.services.crawler import crawl_url_task
    db: Session = SessionLocal()
    try:
        logger.info(f"Worker processing crawl task for URL: {url} (max_depth={max_depth})...")
        crawled_urls = crawl_url_task(db, seed_url=url, max_depth=max_depth)
        logger.info(f"Successfully finished crawl task for {url}. Total pages crawled: {len(crawled_urls)}")
    except Exception as e:
        logger.exception(f"Fatal error while worker executed crawl task for {url}: {e}")
        raise
    finally:
        db.close()

# Register local crawl thread runner callback in publisher module
register_local_crawl_worker_callback(process_crawl_task)


def _get_retry_count(properties: pika.BasicProperties) -> int:
    """Extract the x-retry-count from message headers, defaulting to 0."""
    if properties.headers and "x-retry-count" in properties.headers:
        return int(properties.headers["x-retry-count"])
    return 0


def _republish_with_backoff(channel, body: bytes, properties: pika.BasicProperties, retry_count: int, queue_name: str = MAIN_QUEUE):
    """Republish a message with incremented retry count and exponential backoff delay."""
    backoff_seconds = min(2 ** retry_count, 60)  # 1s, 2s, 4s … capped at 60s
    logger.info(f"Retrying message on queue '{queue_name}' (attempt {retry_count + 1}/{MAX_RETRIES}) after {backoff_seconds}s backoff")
    time.sleep(backoff_seconds)

    new_headers = dict(properties.headers) if properties.headers else {}
    new_headers["x-retry-count"] = retry_count + 1

    channel.basic_publish(
        exchange="",
        routing_key=queue_name,
        body=body,
        properties=pika.BasicProperties(
            delivery_mode=2,
            headers=new_headers,
        ),
    )

def on_message_callback(ch, method, properties, body):
    retry_count = _get_retry_count(properties)
    try:
        payload = json.loads(body.decode())
        doc_id = payload.get("document_id")
        if doc_id:
            process_document(doc_id)
        # Success — acknowledge the message
        ch.basic_ack(delivery_tag=method.delivery_tag)
    except Exception as e:
        logger.error(f"Error handling message (retry {retry_count}/{MAX_RETRIES}): {str(e)}")
        # ACK the current message so it doesn't loop via DLX automatically
        ch.basic_ack(delivery_tag=method.delivery_tag)
        if retry_count < MAX_RETRIES:
            # Republish with incremented retry count and exponential backoff
            _republish_with_backoff(ch, body, properties, retry_count)
        else:
            # Exhausted retries — NACK without requeue to send to DLQ
            logger.error(f"Max retries ({MAX_RETRIES}) exceeded. Sending message to DLQ.")
            ch.basic_publish(
                exchange=DLX_EXCHANGE,
                routing_key=DLQ_QUEUE,
                body=body,
                properties=pika.BasicProperties(
                    delivery_mode=2,
                    headers=dict(properties.headers) if properties.headers else {"x-retry-count": retry_count},
                ),
            )
            # Set Document status to FAILED and log Audit failure
            try:
                db_session = SessionLocal()
                try:
                    payload = json.loads(body.decode())
                    doc_id = payload.get("document_id")
                    doc = db_session.query(Document).filter(Document.id == doc_id).first()
                    if doc:
                        doc.status = DocumentStatus.FAILED
                        db_session.commit()
                        
                        # Audit failure
                        audit = AuditLog(
                            document_id=doc.id,
                            action="SYSTEM_PROCESSING_FAILED",
                            details={
                                "error": str(e),
                                "error_type": type(e).__name__,
                                "retries": retry_count
                            }
                        )
                        db_session.add(audit)
                        db_session.commit()
                finally:
                    db_session.close()
            except Exception as db_err:
                logger.error(f"Failed to record failure status in worker callback: {db_err}")


def on_crawl_message_callback(ch, method, properties, body):
    retry_count = _get_retry_count(properties)
    try:
        payload = json.loads(body.decode())
        url = payload.get("url")
        max_depth = payload.get("max_depth", 2)
        if url:
            process_crawl_task(url, max_depth=max_depth)
        ch.basic_ack(delivery_tag=method.delivery_tag)
    except Exception as e:
        logger.error(f"Error handling crawl message (retry {retry_count}/{MAX_RETRIES}): {str(e)}")
        ch.basic_ack(delivery_tag=method.delivery_tag)
        if retry_count < MAX_RETRIES:
            _republish_with_backoff(ch, body, properties, retry_count, queue_name=CRAWL_QUEUE)
        else:
            logger.error(f"Max retries ({MAX_RETRIES}) exceeded for crawl task. Sending message to DLQ.")
            ch.basic_publish(
                exchange=DLX_EXCHANGE,
                routing_key=DLQ_QUEUE,
                body=body,
                properties=pika.BasicProperties(
                    delivery_mode=2,
                    headers=dict(properties.headers) if properties.headers else {"x-retry-count": retry_count},
                ),
            )


def on_webhook_callback(ch, method, properties, body):
    from app.services.webhook import _send_webhook_request_sync
    retry_count = 0
    if properties.headers and "x-retry-count" in properties.headers:
        retry_count = int(properties.headers["x-retry-count"])
    
    try:
        payload_data = json.loads(body.decode())
        cfg_id = payload_data.get("webhook_config_id")
        url = payload_data.get("url")
        event_type = payload_data.get("event_type")
        payload = payload_data.get("payload")
        idempotency_key = payload_data.get("idempotency_key")
        
        success = _send_webhook_request_sync(cfg_id, url, event_type, payload, idempotency_key, retry_count + 1)
        if success:
            ch.basic_ack(delivery_tag=method.delivery_tag)
        else:
            raise RuntimeError("Webhook delivery failed.")
    except Exception as e:
        logger.error(f"Error executing webhook dispatch (retry {retry_count}): {e}")
        ch.basic_ack(delivery_tag=method.delivery_tag)
        
        backoffs = [5.0, 30.0, 300.0]
        if retry_count < len(backoffs):
            delay = backoffs[retry_count]
            logger.info(f"Scheduling webhook retry in {delay} seconds...")
            time.sleep(delay)
            
            new_headers = dict(properties.headers) if properties.headers else {}
            new_headers["x-retry-count"] = retry_count + 1
            
            ch.basic_publish(
                exchange="",
                routing_key="webhook_queue",
                body=body,
                properties=pika.BasicProperties(
                    delivery_mode=2,
                    headers=new_headers
                )
            )
        else:
            logger.error(f"Webhook dispatch exhausted all {len(backoffs)} retry attempts.")


def rabbitmq_worker_main():
    """
    Main loop listening to RabbitMQ messages.
    """
    logger.info("Starting RabbitMQ background worker daemon...")
    while True:
        try:
            credentials = pika.PlainCredentials(settings.RABBITMQ_USER, settings.RABBITMQ_PASS)
            parameters = pika.ConnectionParameters(
                host=settings.RABBITMQ_HOST,
                port=settings.RABBITMQ_PORT,
                credentials=credentials,
                heartbeat=600,
                blocked_connection_timeout=300
            )
            connection = pika.BlockingConnection(parameters)
            channel = connection.channel()

            # Graceful shutdown handler
            import signal
            def handle_shutdown(signum, frame, channel=channel, connection=connection):
                logger.info("Received termination signal. Shutting down worker gracefully...")
                try:
                    if channel.is_open:
                        channel.stop_consuming()
                    if connection.is_open:
                        connection.close()
                except Exception as ex:
                    logger.error(f"Error during shutdown: {ex}")
            signal.signal(signal.SIGTERM, handle_shutdown)
            signal.signal(signal.SIGINT, handle_shutdown)

            # Declare dead-letter exchange & queue
            channel.exchange_declare(exchange=DLX_EXCHANGE, exchange_type="direct", durable=True)
            channel.queue_declare(queue=DLQ_QUEUE, durable=True)
            channel.queue_bind(queue=DLQ_QUEUE, exchange=DLX_EXCHANGE, routing_key=DLQ_QUEUE)

            # Declare main queue with DLX arguments
            channel.queue_declare(
                queue=MAIN_QUEUE,
                durable=True,
                arguments={
                    "x-dead-letter-exchange": DLX_EXCHANGE,
                    "x-dead-letter-routing-key": DLQ_QUEUE,
                    "x-message-ttl": 86400000,  # 24 hours TTL in milliseconds
                },
            )
            # Declare crawl queue with DLX arguments
            channel.queue_declare(
                queue=CRAWL_QUEUE,
                durable=True,
                arguments={
                    "x-dead-letter-exchange": DLX_EXCHANGE,
                    "x-dead-letter-routing-key": DLQ_QUEUE,
                    "x-message-ttl": 86400000,
                },
            )
            channel.queue_declare(queue="webhook_queue", durable=True)
            channel.basic_qos(prefetch_count=1)

            channel.basic_consume(queue=MAIN_QUEUE, on_message_callback=on_message_callback)
            channel.basic_consume(queue=CRAWL_QUEUE, on_message_callback=on_crawl_message_callback)
            channel.basic_consume(queue="webhook_queue", on_message_callback=on_webhook_callback)
            logger.info("Worker daemon connected to RabbitMQ. Listening for messages...")
            channel.start_consuming()

        except pika.exceptions.AMQPConnectionError:
            logger.warning("RabbitMQ connection refused. Re-trying in 5 seconds...")
            time.sleep(5)
        except KeyboardInterrupt:
            logger.info("Worker stopped by user request.")
            break
        except Exception as e:
            logger.error(f"Unexpected worker error: {str(e)}. Restarting connection loop in 5 seconds...")
            time.sleep(5)

if __name__ == "__main__":
    rabbitmq_worker_main()

